### ISSUE TITLE
Line 123:  authenticated_client.py invalid number of arguments

### ISSUE THREAD

**Issue by derenma** [danpaquin/gdax-python#120]
Howdy! Just a quick fix line 123 of authenticated_client.py:
from: self.paginate_orders(result, r.headers['cb-after'])
to: self.paginate_orders(product_id, result, r.headers['cb-after'])

-----

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\endian0A\Documents\Dev\gdax-bot\TradeBot\pill.py", line 153, in a_buy
    self.account.update_orders()
  File "C:\Users\endian0A\Documents\Dev\gdax-bot\TradeBot\account.py", line 89, in update_orders
    self.orders = self.client.get_orders()
  File "C:\Users\endian0A\Documents\Dev\gdax-bot\gdax\authenticated_client.py", line 111, in get_orders
    self.paginate_orders(product_id, result, r.headers['cb-after'])
  File "C:\Users\endian0A\Documents\Dev\gdax-bot\gdax\authenticated_client.py", line 123, in paginate_orders
    self.paginate_orders(result, r.headers['cb-after'])
TypeError: paginate_orders() takes exactly 4 arguments (3 given)

**Comment by derenma** [comment]
Going to open a quickie PR in a sec...

**Comment by danpaquin** [comment]
Thank you for sharing!
