### ISSUE TITLE
how to reconnect after stop retrieve market data from websocket server

### ISSUE THREAD

**Issue by JMedon** [danpaquin/gdax-python#194]
Hi 
every several hours I'am loosing connection and I receive below error

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\JM\Documents\GitHub\gdax-python\gdax\websocket_client.py", line 87, in _listen
    self.ws.ping("keepalive")
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_core.py", line 275, in ping
    self.send(payload, ABNF.OPCODE_PING)
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_core.py", line 234, in send
    return self.send_frame(frame)
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_core.py", line 259, in send_frame
    l = self._send(data)
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_core.py", line 423, in _send
    return send(self.sock, data)
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_socket.py", line 116, in send
    return sock.send(data)
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] The existing connection was sharply closed by the remote host - data: None
-- SERVERS STOPS! TRY TO RECONNECT  #--

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\JM\Documents\GitHub\gdax-python\gdax\websocket_client.py", line 43, in _go
    self._listen()
  File "C:\Users\JM\Documents\GitHub\gdax-python\gdax\websocket_client.py", line 95, in _listen
    self.on_error(e)
  File "C:\Users\JM\Documents\GitHub\gdax-python\gdax\websocket_client.py", line 132, in on_error
    self.close()
  File "C:\Users\JM\Documents\GitHub\gdax-python\gdax\websocket_client.py", line 112, in close
    self.thread.join()
  File "C:\Users\JM\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread`

I dont know how to implement the code to  auto reconnect connection to websocket API server.

I read
https://github.com/danpaquin/gdax-python/issues/89
https://github.com/danpaquin/gdax-python/issues/168

can you show example how to add it?
thanks in advance!

**Comment by biwa7636** [comment]
I have a hack where I run another script to periodically (say every minute) check the number of records within Mongodb, where I am storing all the documents from websocket. If within a certain window (say 5 seconds) the records count at the beginning of the window and the end are the same. I am confident the pipeline is broken. Then I will using subprocess to kill the running script and then restart the same script appending existing data to another mongo collection. 
I know this is flawed because that one minute gap is gone forever. However, I tried to periodically get a copy of level 3 order book so that I can rebuild the latest order book if needed.

**Comment by JMedon** [comment]
Hi I dont know how to implement it.
Can you show example how to do that?
thanks in advance

**Comment by smilerz** [comment]
@JMedon 
It's not perfect, but I have the code below which works more often than not.
```
wsClient.start()
while True:
    if wsClient.stop:
        wsClient.close()
        wsClient.start()
    sleep(1)
```

**Comment by s-ben** [comment]
@smilerz , does the above code fail if there client returns an error?

**Comment by smilerz** [comment]
An unhandled error is likely to break it, but I haven't run into that condition yet.

**Comment by danpaquin** [comment]
Thank you @smilerz for your contributions.  I'm closing this out for now.
