### ISSUE TITLE
Trouble with Authenticated Client

### ISSUE THREAD

**Issue by JoeSchm** [danpaquin/gdax-python#195]
I'm having trouble with the authticated client. I'm trying to run the module with the command below using Ubuntu and getting the response back. I'm new here. Any help would be appreciated. Is there a typo in the authnticated client?I'm not sure how to run this.

Thanks,

(xenial)xxxxx@localhost:~/Code/gdax-python-master/gdax$ python3 -m authenticated_client.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/xxxxx/Code/gdax-python-master/gdax/authenticated_client.py", line 15, in <module>
    from gdax.gdax_auth import GdaxAuth
ModuleNotFoundError: No module named 'gdax.gdax_auth'

**Comment by smalbadger** [comment]
I think this is what you're looking for. I took this code out of my program successfully authenticates the client. I replaced my personal API info for obvious reasons.

import gdax
key = "XXXXXXXXXXX"
secret = "XXXXXXXXXXX"
passphrase= "XXXXXXXXXXXXXXXXXXX"
Client = gdax.AuthenticatedClient(key, secret, passphrase)

**Comment by JoeSchm** [comment]
Thanks smalbadger. The b64 threw me off. When I run the below commands with the sandbox api given I get the below errors. Is this because I need to call out the sandbox api everywhere I see a reference to the api url in the authenticated client module?

**Comment by JoeSchm** [comment]
>>> auth_client = gdax.AuthenticatedClient(api_key, secret_key, passphrase,api_url="https://api-public.sandbox.gdax.com")
>>> auth_client.get_accounts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gdax/authenticated_client.py", line 28, in get_accounts
    return self.get_account('')
  File "/usr/local/lib/python3.6/site-packages/gdax/authenticated_client.py", line 23, in get_account
    r = requests.get(self.url + '/accounts/' + account_id, auth=self.auth)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 543, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.6/site-packages/gdax/authenticated_client.py", line 298, in __call__
    hmac_key = base64.b64decode(self.secret_key)
  File "/usr/local/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by smalbadger** [comment]
Sorry JoeSchm, I don't know what you mean by "call out the sandbox api". I'm a newbie myself. If I had to guess, I would say you probably altered either the API key, secret, or passphrase, but most likely the secret. Did you take off the "==" sign at the end or something? My secret is 88 characters I believe.

**Comment by JoeSchm** [comment]
This may have worked for me. I did omit to == at the end. My secret is now 88 characters. I dont get the same errors now. I think it is working but the sandbox is unavailable now so I get a message about timing out. I do get errors though because of it. I thintk the sandbox is down because of the bitcoin cash roll out. The sandbox is a separate api that gdax set up so that you can test your code without using real money. I supposedly not very good to test trading strategies but just that your bot behaves as expected. When the sandbox starts working again I'll test this again and close this issue.

**Comment by smalbadger** [comment]
Glad it worked. Yeah, I tried using the sandbox a while ago, and I couldn't do anything other than connect and get prices for some reason. I'm just making an option to do paper trades (fake trades) in my program to make sure that the algorithm works as planned, but I'm connecting to the actual GDAX website.

**Comment by JoeSchm** [comment]
I tried the regul

**Comment by JoeSchm** [comment]
I got this working on the regular api. Thanks.
