### ISSUE TITLE
Connection is already closed error

### ISSUE THREAD

**Issue by slazarov** [danpaquin/GDAX-Python#53]
Hello, I am receiving the following error with the latest 0.3.1 version.
Could this be cause by a connection drop?

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/GDAX/WebsocketClient.py", line 54, in _listen
    msg = json.loads(self.ws.recv())
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/GDAX/WebsocketClient.py", line 28, in _go
    self._listen()
  File "/usr/local/lib/python3.6/site-packages/GDAX/WebsocketClient.py", line 57, in _listen
    self.close()
  File "/usr/local/lib/python3.6/site-packages/GDAX/WebsocketClient.py", line 68, in close
    self.thread.join()
  File "/usr/local/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by danpaquin** [comment]
This is the same error as #51.  Please close this out if so.

**Comment by garbb** [comment]
I know that you have closed this and it is not a problem with your code but I was wondering if anyone knew of any possible workaround for this?
Normally I would use `try: except:` for this kind of thing to have it try to reconnect or something but because this exception seems to happen in some other library and not in the code I wrote I am not sure if this will work?

**Comment by danpaquin** [comment]
Issue #51 addresses this with a little more detail. We'll have to look into this.
