### ISSUE TITLE
OrderBook init failed

### ISSUE THREAD

**Issue by kingsfield** [danpaquin/gdax-python#99]
```
Traceback (most recent call last):
  File "/Users/kingsfield/workspace/quant/spider/bitcoin/websocket_coinbase.py", line 37, in <module>
    order_book = gdax.OrderBook(product_id='BTC-USD')
  File "/usr/local/lib/python2.7/site-packages/gdax/order_book.py", line 20, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'
```

**Comment by metachris** [comment]
Duplicate of #98

**Comment by danpaquin** [comment]
product_id has been removed from init and you must add it to every call. This is to ensure no mistakes are made when querying multiple products

**Comment by Vacant0mens** [comment]
I'm getting this error using the example in the `README.md`. Is that example outdated? What's the proper syntax for calling the OrderBook class?
